version: '3'

# valores setados como variavel ${} , dever ser informadas no arquivo .env

# Contaniner api adonis
services:
  site-api:
    container_name: site-api
    build: .
    environment:
      TZ: ${APP_TIME_ZONE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
    networks: 
      - docker-site-api
    depends_on:
        - db-site-api       

# Container Mysql
  db-site-api:    
    container_name: db-site-api
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}      
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${DB_TIME_ZONE}
    ports:        
        - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./database/docker/volume/db:/var/lib/mysql
      
    networks: 
      - docker-site-api
      
      # Network
networks:
 docker-site-api: